id: A5CC455FF
title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas, from
  the Heart Essence of the Vast Expanse'
type: translation
pechas:
- IB9CD8DC9
- I8DCEB997
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:43:18.341279
  last_modified_at: 2023-01-04 12:43:18.341300
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IB9CD8DC9/F84B: '8166'
  I8DCEB997/56E2: '8166'
